services:
  qdrant:
    image: qdrant/qdrant:v1.7.4
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage_video_retrieval:/qdrant/storage

  indexer:
    build: .
    command: ["python", "backend/app/builder/run_all.py"]
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    depends_on:
      - qdrant

  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
    depends_on:
      indexer:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
